# Generated by Django 3.0 on 2020-01-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('positions', models.CharField(max_length=255)),
                ('min_experience', models.CharField(max_length=255)),
                ('special_ability', models.CharField(max_length=255)),
                ('sport', models.CharField(choices=[('fotboll', 'Fotboll')], max_length=255)),
                ('slug', models.SlugField()),
                ('ad_id', models.PositiveSmallIntegerField(unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
