# Generated by Django 3.0 on 2020-01-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.IntegerField(unique=True),
        ),
    ]
