# Generated by Django 3.0 on 2020-01-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hittalaget.teams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField()),
                ('founded', models.PositiveSmallIntegerField()),
                ('home', models.CharField(max_length=255)),
                ('is_looking', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('sport', models.CharField(choices=[('fotboll', 'Fotboll')], max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='images/teams/default.jpg', null=True, upload_to=hittalaget.teams.models.get_upload_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'sport'), name='unique_team'),
        ),
    ]
